### PR TITLE
Directv Support???

### PR DESCRIPTION
**Pull request by bklavet**
Hey there, found your Roku repository and got to thinking Directv should work as well.  I have been able to control my receiver through the web with this format http://xxx.xxx.xxx.xxx:8080/remote/processKey?key=(key)&hold=keyPress

I made changes to  the Index file to support the path and port difference.  however.  I can't get aws lambda to take it and POST.  Care to take a look and tell me what I have wrong?  I am thinking with your template on Roku, that any device that can be controlled by POST should be able to have a skill built similar.  

disclaimer (I am really new to GitHub and how this all works, I hope I didn't screw up your page!) also I am a hack and just sort of fumbling through this all. )

### CODE REVIEW

**Comment by MrEggsalad** [comment]
Anything should be similar. My guess is that your code isn't waiting for the request to finish before it ends and so it isn't working properly.

**Comment by bklavet** [comment]
Thanks for the quick response!  Every test utterance I issue in ASK gets a "response is invalid"  
How would I alter this index file so it waits?  Did you have issue with this for your Roku?  I didn't think I changed much sept for the cases.  Another question is line 16 of your index should (./AlexaSkill) be changed to something else or is that the way it is supposed to be?  Line 6 and line 11 look to be the only places in that file that need to be changed.  

Thanks for the feedback, and please forgive my ignorance I am really hoping to get this to work and your project looks to be the most promising.  I appreciate you putting it out on git hub.

Brian

**Comment by bklavet** [comment]
I received this in Lambda when I tested it:
error log on lambda
lambda test sample

**Comment by MrEggsalad** [comment]
The error message you got says there is a syntax error in your code, suggesting that there is some error in your JavaScript rather than a logic issue.

**Comment by bklavet** [comment]
MrEggsalad Thank you!  I went back through the zip file and found that I had not put my app ID in ""

I am no longer getting the syntax error!  However I am now getting this:
app id error

So I double checked my application ID and it is correct.  I only have that entered in the index.js file.  I didn't see anyplace in the AlexaSkill file that needed the application ID entered.  For the index file I have my application ID listed like this:
var APP_ID = "amzn1.echo-sdk-ams.app.36b4e5ea-ed3d-4a86-af68-xxxxxxxxxxxx";

**Comment by bklavet** [comment]
hey there found my problem with the app ID... It was me, had a space in there also change the DirectvIntent back to RokuIntent and now I am getting a response from lambda in the alexa skill kit!
success

**Comment by bklavet** [comment]
MrEggsalad,  Thanks again for your feedback on this.  I loaded your Alexaskill and Index with no changes sept my app ID and IP.  I am seeing the same response in testing.  It does not appear that the index file is sending a url.  however it will kick back the default message to alexa if a test command is not found in the "case" arguments.  Do you know why the url's aren't kicking out?  it looks like for your Roku project  if a person tells Alexa to ask Roku to "play"  the url that should come from lambda would be " http://xxx.xxx.xxx.xxx:8060/keypress/Play" .  The response I am getting in the alexa testing is (lambda response "response is invalid). In my alteration of the index file I have only added to the path to allow for it to interact with directv I am seeing the same results.  Is there anything that may have changed in your index file you have on GitHub?  if you test through the developer console and text 
"play"  what is your response from lambda?  

Thanks for your patience with me, like I said before I am just trying to get this to make sense,  your index file is written really nicely I just can't figure out why the POST isn't posting.

**Comment by bklavet** [comment]
MrEggsalad,
I am having still not able to send a URL from aws lambda though everything would seems like it should.  
case "dash":
                        var options = {
                                host: local_ip,
                                port: '8080',
                                path: '/remote/processKey?key=dash&hold=keyPress',
                                method: 'POST'
                        };
                        
                        var req = http.request(options, satisfyAlexa);
                        console.log(req);
                        req.end(response.tell("OK"));
                break;

I added a console.log(req); and when I test in lambda I see the ip:port and path.  Did you have to add an API endpoint to issue a POST HTTP request?  For the above example I get alexa to say "OK".  So it looks like the code is reading through to the req.end(response.tell("OK"));

**Comment by MrEggsalad** [comment]
Everything with Alexa should be treated like a conversation. I think in my code I have an empty response.tell just so she knows the transaction is done.

**Comment by bklavet** [comment]
Thanks I will keep digging.  Did you use api endpoint in lambda though?

**Pull request closed without merging**
